<!-- Añadir comentarios -->
<form action="index.php?controller=comentarios&action=insert" method="post">
        <div class="form-group">
                <label for="exampleTextarea" class="labelNormal">Añadir comentario</label>
                <textarea class="form-control" id="exampleTextarea" name="mensaje" rows="3" required></textarea>
        </div>

        <button id="añadirComentario" type="submit" class="btn btn-secondary mb-3" name="insert">Enviar</button>

</form>
<!-- Fin añadir comentarios -->