<!-- Button to Open the Modal -->
<button type="button" class="btn btn-secondary mb-3" data-toggle="modal" data-target="#ModalCrearEquipo">
  Agregar equipo
</button>

<!-- The Modal -->
<div class="modal fade" id="ModalCrearEquipo">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Introduce los datos del nuevo equipo</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form action="index.php?controller=equipos&action=insert" method="post">

          <div class="form-group">
            <label class="labelNormal" for="nombre">Nombre del equipo:</label>
            <input type="text" name="nombre" value="" required>
          </div>


          <button type="submit" class="btn btn-secondary mb-2" name="insert">Guardar</button>

        </form>
      </div>



    </div>
  </div>
</div>