<!DOCTYPE html>
<html lang="en">

<head>
  <title>Torneos</title>
  <?php include 'head_view.html';?>

</head>

<body>

  <?php include 'menu_view.phtml';?>

  <div class="container">

    <h2>Deportes</h2>

    <div class="row">
      <div class="col-6">
        <table class="table table-bordered">
          <!-- <tr><td> <a href="index.php?controller=deportes&action=ordPuntosDesc">Marca</a></td><td>Modelo</td><td>Fabricado en</td><td></td></tr> -->
          <tr>
            <th>ID</th>
            <th>Deporte</th>
          </tr>

          <?php
            foreach ($datos as $dato) {
                echo "<tr>
                <td>{$dato['id_deporte']}</td>
                <td>{$dato['nombre']}</td>";
            }
        ?>
        </table>
      </div>

      <div class="col-6">

        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myModal">
          Agregar deporte
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Introduce los datos del nuevo deporte</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <form action="index.php?controller=deportes&action=insert" method="post">
                  <label for="nombre">Nombre del deporte:</label>
                  <input type="text" name="nombre" value="">
                  <br>

                  <input type="submit" name="insert" value="Guardar">

                </form>
              </div>

              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              </div>

            </div>
          </div>
        </div>

      </div>

      <p>
        <a href="index.php?controller=deportes&action=add">Crear torneos</a>
      </p>



    </div>

  </div>
</body>

</html>