<!DOCTYPE html>
<html lang="en">

<head>
  <title>jugadores</title>
  <?php include 'head_view.html';?>
</head>

<body>

  <?php include 'menu_view.phtml';?>


  <div class="container">

    <h2>Jugadores</h2>


    <div class="row">
      <div class="col-12 col-md-8 table-responsive">

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellidos</th>
              <th class='textoCentrado'>Dorsal</th>
              <th>Email</th>
              <th class='textoCentrado'>Sexo</th>
              <th class='textoCentrado'>Equipo</th>
              <th class='textoCentrado'>Eliminar</th>

            </tr>
          </thead>
          <tbody>
            <?php
                foreach ($datos as $dato) {
                     echo "
                     <tr>
                     <td>{$dato['nombrejugador']}
                     </td>

                     <td>
                     {$dato['apellidos']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['dorsal']}
                     </td>

                     <td>
                     {$dato['email']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['sexo']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['nombreequipo']}
                     </td>

                     <td class='textoCentrado'>
                     <a href=\"index.php?controller=jugadores&action=delete&id={$dato['id_jugador']}\"><i class='fas fa-trash-alt'></i></a>
                     </td>
                     
                   </tr>";
                   
                    }
            ?>

          </tbody>
        </table>

      </div>




      <div class="col-12 col-md-4">

        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-secondary mb-3" data-toggle="modal" data-target="#myModal">
          Agregar jugador
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Introduce los datos del nuevo jugador</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <form action="index.php?controller=jugadores&action=insert" method="post">

                  <div class="form-group">
                    <label for="nombre">Nombre:</label>
                    <input type="text" name="nombre" value="" required>
                  </div>

                  <div class="form-group">
                    <label for="apellidos">Apellidos:</label>
                    <input type="text" name="apellidos" value="" required>
                  </div>

                  <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" value="" required>
                  </div>


                  <div class="form-group">
                    <label for="id_equipo">Equipo:</label>
                    <select name="id_equipo">

                      <?php
            foreach ($datosequipos as $datosequipo) {
              echo "<option value={$datosequipo['id_equipo']}>{$datosequipo['nombre']} </option>";
            }  ?>


                    </select>
                  </div>

                  <div class="form-group">
                    <label for="dorsal">Dorsal:</label>
                    <input type="number" name="dorsal" value="" required>
                  </div>

                  <div class="form-group">
                    <label for="sexo">Sexo:</label>

                    <div class="radio">
                      <label>
                        <input type="radio" name="sexo" value="M">Masculino</label>
                    </div>
                    <div class="radio">
                      <label>
                        <input type="radio" name="sexo" value="F">Femenino</label>
                    </div>
                  </div>



                  <button type="submit" class="btn btn-secondary" name="insert">Guardar</button>

                </form>
              </div>



            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
  <footer>
    <?php include 'footer_view.html';?> </footer>
</body>

</html>