<!-- Dropdown Administración -->
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
    Zona ADMIN
  </a>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="index.php?controller=jugadores&action=view">Jugadores</a>
    <a class="dropdown-item" href="index.php?controller=comentarios&action=view">Directo</a>
    <a class="dropdown-item" href="index.php?controller=equipos&action=view">Equipos</a>
    <a class="dropdown-item" href="index.php?controller=usuarios&action=registroView">Agregar Usuario</a>
    <a class="dropdown-item" href="index.php?controller=usuarios&action=logout">Logout</a>
  </div>
</li>