<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="index.php">GMSTorneos</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="index.php?controller=comentarios&action=view">Directo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="index.php?controller=equipos&action=view">Clasificación</a>
      </li>

      <?php if (isset ($_SESSION['usuario'])) { include 'menuAdmin_view.phtml'; } ?>

      <?php if (!isset ($_SESSION['usuario'])) { echo " 

      <li class='nav-item'>
        <a class='nav-link' href='index.php?controller=usuarios&action=loginView'>
        Login
         </a>
      </li>

      "; } ?>

      <li class="nav-item">
        <a class="nav-link" href="#">
          <?php if (isset ($_SESSION['usuario'])) { echo "Hola, ".$_SESSION['usuario']; } ?>
        </a>
      </li>

    </ul>
  </div>
</nav>