<!DOCTYPE html>
<html lang="en">

<head>
  <title>Torneos</title>
  <?php include 'head_view.html';?>
</head>

<body>

  <?php include 'menu_view.phtml';?>


  <div class="container">



    <div class="row">
      <div class="col-12">

        <h2 class="textoCentrado titulo">GMS Torneos </h2>
        <h5 class="textoCentrado descripcion">Bienveidos a torneos GMS, desde esta página podrás seguir en directo el torneo de fútbol de tu instituto</h5>

      </div>
    </div>

  </div>

  <div id="demo" class="carousel slide" data-ride="carousel" data-interval="3000">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="img/futbol2.jpg" alt="Los Angeles" width="1060" height="500">
      </div>
      <div class="carousel-item">
        <img src="img/futbol.jpg" alt="Chicago" width="1060" height="500">
      </div>
      <div class="carousel-item">
        <img src="img/futbol-dos-1068x649.jpg" alt="New York" width="1060" height="500">
      </div>
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>

  <footer>
    <?php include 'footer_view.html';?> </footer>
</body>

</html>